### ISSUE TITLE
License file missing inside pypi package

### ISSUE THREAD

**Issue by monzelr** [shpaker/winregistry#13]
Hi,

in the current version 1.1.1 pypi package, the license file is missing:

![image](https://github.com/shpaker/winregistry/assets/60315601/7dbfa889-8445-4c64-8359-9189eefc0523)

Best,
Rune

**Comment by shpaker** [comment]
Hi,
fixed in version ^2.0
<img width="413" alt="image" src="https://github.com/user-attachments/assets/784791cd-2861-4bc3-9fc7-b8598360ab52">
